version: "3.8"

services:
  db:
    image: postgres
    container_name: softteco_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - softteco_postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: softteco_pgadmin
    restart: always
    ports:
      - "9011:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - softteco_pgadmin:/var/lib/pgadmin

volumes:
  softteco_postgres:
  softteco_pgadmin:
